#!/bin/bash

# Run script as root for apt install.
if [ $(whoami) != "root" ]
then
    echo "You must run this script as root."
    exit 1
fi

apt install -y gir1.2-webkit2-4.0 \
    gir1.2-poppler-0.18 \
    sox \
    python3-gst-1.0 \
    python3-gdbm \
    python3-libdiscid \
    python3-gi-cairo \
    python3-fuzzywuzzy \
    python3-levenshtein \
    python3-musicbrainzngs \
    python3-unidecode

# Prepare to drop privilege to user.
user=$(who -m | awk '{ print $1 }')
echo -e "\nWill install wax as user $user. Type return to proceed or ^c to exit."
read

sudo -i -u $user bash << EOF

# Create virtual environment in wax and install requirements.
echo "Creating virtual environment"
python3.11 -m venv ~/.venv

echo "include-system-site-packages = true" >> ~/.venv/pyvenv.cfg

echo "Installing requirements"
python3.11 -m pip install -r requirements.txt

[ ! -d ~/.themes ] && mkdir ~/.themes
rm -rf ~/.themes/Materia-Manjaro-Dark-gtk
mv Materia-Manjaro-Dark-gtk ~/.themes
rm -f ~/.config/gtk-3.0/gtk.css

mv recordings ~/wax
ln -s ~/wax/recordings ~/wax-config/recordings
mkdir ~/wax/recordings/{images,documents,sound}

mkdir -p ~/wax/.config/{log,queuefiles,transfer}
mv completers ~/wax/.config

EOF

chown root:root waxstarter
mv waxstarter /usr/local/bin/wax
ln /usr/local/bin/wax /usr/local/bin/waxconfig

